apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: testProject
  name: testProject
  annotations:
    kubernetes.io/change-cause: "{timestamp} Deployed commit id: {commit}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testProject
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testProject
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - testProject
              topologyKey: kubernetes.io/hostname
      containers:
      - name: testProject
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        imagePullPolicy: IfNotPresent
        image: https://quay.io/volvocars/testProject/testProject:{commit}
        ports:
        - containerPort: 80
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: testProject
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testProject
  type: ClusterIP